### ISSUE TITLE
What fps used to convert mp4 --> png?

### ISSUE THREAD

**Issue by andrewjong** [RenYurui/Global-Flow-Local-Attention#28]
Hi,

I am interested in Pose-Guided Person Image Animation. I downloaded the Fashion Video Dataset via the instructions, and received many *.mp4 files. I figure I must convert these to *.png, so I wrote a little script that uses `ffmpeg`. However, after converting at 29.97 frames per second (the fps of the video), I found that the number of frames extracted do not match the number of keypoints (it seems I have too many).

At what fps did you use to convert the *.mp4 to *.png, please? I want to make sure the timing of my extracted frames match the keypoints.

**Comment by RenYurui** [comment]
Hi!
Thanks for your question.
We have updated the code. Please use ./script/extract_video_frames.py to extract video frames from mp4 videos. 
``` bash
python ./script/extract_video_frames.py \
--frame_root=[path to write the video frames] \
--video_path=[path to the mp4 files]
```

**Comment by andrewjong** [comment]
Wow, excellent! Thanks very much.

**Comment by andrewjong** [comment]
Hi Ren,

I ran the script, I still get unmatching lengths. I got 378 frames in `train_A/91MTHBRuoeS`, but 346 entries in `train_video2d/91MTHBRuoeS`. Do you think the dataset download might have changed the duration of the videos?

**Comment by RenYurui** [comment]
Hi! 
I find it is a bug of Opencv. Some final frames will be dropped by Opencv without warnings. Meanwhile, different Opencv versions result in different frame numbers. Check [here](https://github.com/opencv/opencv/issues/9053) for details.
I change the code to use Skvideo to extract video frames.
Thanks for your question.
